#Requires -Version 5.1
<#
.SYNOPSIS
    Install grok on Windows.

.DESCRIPTION
    Copies grok.exe to %USERPROFILE%\.grok\bin\, adds that directory to the
    current user's PATH, and writes a starter ~/.grok/config.toml if one does
    not already exist.

.PARAMETER GrokExe
    Path to grok.exe.  Defaults to a file named "grok.exe" in the same
    directory as this script.

.PARAMETER ApiKey
    DeepSeek API key (sk-...).  If omitted you will be prompted; you can also
    set %DEEPSEEK_API_KEY% before running and skip the prompt entirely.

.PARAMETER Model
    Default model ID sent to the API.  Defaults to "deepseek-v4-pro".

.EXAMPLE
    .\install.ps1
    .\install.ps1 -GrokExe "C:\Downloads\grok.exe" -Model deepseek-v4-flash
#>
[CmdletBinding()]
param(
    [string] $GrokExe  = (Join-Path $PSScriptRoot "grok.exe"),
    [string] $ApiKey   = $env:DEEPSEEK_API_KEY,
    [string] $Model    = "deepseek-v4-pro"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── helpers ──────────────────────────────────────────────────────────────────
function Write-Step  { param($msg) Write-Host "  → $msg" -ForegroundColor Cyan }
function Write-OK    { param($msg) Write-Host "  ✓ $msg" -ForegroundColor Green }
function Write-Warn  { param($msg) Write-Host "  ! $msg" -ForegroundColor Yellow }
function Write-Fatal { param($msg) Write-Host "`n✗ $msg`n" -ForegroundColor Red; exit 1 }

# ── banner ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  grok — Windows Installer" -ForegroundColor White
Write-Host "  ─────────────────────────────────────────────" -ForegroundColor DarkGray
Write-Host ""

# ── 1. locate binary ─────────────────────────────────────────────────────────
Write-Step "Locating grok.exe …"
if (-not (Test-Path $GrokExe)) {
    Write-Fatal "grok.exe not found at '$GrokExe'.`n  Pass -GrokExe <path> or place grok.exe next to this script."
}
Write-OK "Found: $GrokExe ($([math]::Round((Get-Item $GrokExe).Length / 1MB, 1)) MB)"

# ── 2. install to ~/.grok/bin/grok.exe ───────────────────────────────────────
Write-Step "Installing to %USERPROFILE%\.grok\bin\ …"
$installDir = Join-Path $env:USERPROFILE ".grok\bin"
New-Item -ItemType Directory -Force -Path $installDir | Out-Null
$dest = Join-Path $installDir "grok.exe"
Copy-Item $GrokExe $dest -Force
Write-OK "Installed: $dest"

# ── 3. add to user PATH ───────────────────────────────────────────────────────
Write-Step "Updating user PATH …"
$userPath = [System.Environment]::GetEnvironmentVariable("PATH", "User") ?? ""
$segments  = $userPath -split ";" | Where-Object { $_ -ne "" }
if ($segments -contains $installDir) {
    Write-OK "Already in PATH — no change needed."
} else {
    $newPath = ($segments + $installDir) -join ";"
    [System.Environment]::SetEnvironmentVariable("PATH", $newPath, "User")
    # Also update the current session so you can use grok right away.
    $env:PATH = "$env:PATH;$installDir"
    Write-OK "Added to PATH: $installDir"
    Write-Warn "Restart any open terminals to pick up the PATH change."
}

# ── 4. API key ────────────────────────────────────────────────────────────────
Write-Step "Checking API key …"
if (-not $ApiKey) {
    Write-Host ""
    Write-Host "  Your DeepSeek API key is required." -ForegroundColor White
    Write-Host "  Get one at: https://platform.deepseek.com/api_keys" -ForegroundColor DarkGray
    Write-Host ""
    $secKey = Read-Host "  Enter API key (sk-...)" -AsSecureString
    $ApiKey  = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
                   [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secKey))
}
if (-not $ApiKey -or $ApiKey.Length -lt 10) {
    Write-Warn "No API key provided.  Edit ~/.grok/config.toml later to add one."
} else {
    Write-OK "API key received (length: $($ApiKey.Length))."
}

# ── 5. write config.toml (skip if exists) ─────────────────────────────────────
Write-Step "Writing ~/.grok/config.toml …"
$grokHome   = Join-Path $env:USERPROFILE ".grok"
$configPath = Join-Path $grokHome "config.toml"
New-Item -ItemType Directory -Force -Path $grokHome | Out-Null

if (Test-Path $configPath) {
    Write-OK "Config already exists — not overwriting: $configPath"
} else {
    $apiKeyLine = if ($ApiKey -and $ApiKey.Length -ge 10) {
        "api_key     = `"$ApiKey`""
    } else {
        '# api_key  = "sk-..."   # ← paste your key here, or set DEEPSEEK_API_KEY env var'
    }

    $config = @"
# ~/.grok/config.toml
# Generated by install.ps1 — edit freely.

# ---------------------------------------------------------------------------
# Authentication — use API key, skip xAI login
# ---------------------------------------------------------------------------
[auth]
preferred_method = "api_key"

# ---------------------------------------------------------------------------
# Default model
# ---------------------------------------------------------------------------
[models]
default = "$Model"

# ---------------------------------------------------------------------------
# DeepSeek V4 Pro  (frontier reasoning / agentic coding, 1 M context)
# ---------------------------------------------------------------------------
[model.deepseek-v4-pro]
model          = "deepseek-v4-pro"
base_url       = "https://api.deepseek.com/v1"
name           = "DeepSeek V4 Pro"
description    = "DeepSeek-V4-Pro — frontier reasoning and agentic coding"
api_backend    = "chat_completions"
env_key        = "DEEPSEEK_API_KEY"
context_window = 900000
$apiKeyLine

# ---------------------------------------------------------------------------
# DeepSeek V4 Flash  (fast / low-cost, reasoning close to Pro)
# ---------------------------------------------------------------------------
[model.deepseek-v4-flash]
model          = "deepseek-v4-flash"
base_url       = "https://api.deepseek.com/v1"
name           = "DeepSeek V4 Flash"
description    = "DeepSeek-V4-Flash — fast and economical"
api_backend    = "chat_completions"
env_key        = "DEEPSEEK_API_KEY"
context_window = 900000
"@
    Set-Content -Path $configPath -Value $config -Encoding UTF8
    Write-OK "Created: $configPath"
}

# ── 6. verify ─────────────────────────────────────────────────────────────────
Write-Step "Verifying installation …"
$version = & $dest --version 2>&1 | Select-Object -First 1
Write-OK "grok $version"

# ── done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  Quick start:" -ForegroundColor White
Write-Host "    `$env:DEEPSEEK_API_KEY = 'sk-...'   # set once per session" -ForegroundColor DarkGray
Write-Host "    grok                                # launch" -ForegroundColor DarkGray
Write-Host "    grok -p 'Hello'                     # one-shot prompt" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Switch model inside grok:" -ForegroundColor White
Write-Host "    /model deepseek-v4-flash" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Config file: $configPath" -ForegroundColor DarkGray
Write-Host ""
